### ISSUE TITLE
[Enhancement] Add an OpenSearch specification

### ISSUE THREAD

**Issue by Athanasius** [readtedium/udm14#2] opened 2024-05-22 19:30 UTC
Firefox supports OpenSearch specifications so that sites can provide a 'Search Engine', but it's not limited to being for the site itself.

I ran one up for this Google / Web View / udm=14 thing at https://miggy.org/misc/firefox-google-search-no-ai.html , view the source to see how it works (link rel tag to an xml file).

Might be worth adding such so people don't even have to go via your website if using Firefox ?

**Comment by readtedium** [comment] 2024-05-22 19:31
@xerz-one is adding this per a recent comment of theirs.

**Comment by xerz-one** [comment] 2024-05-22 21:40
#6 is done, please review to see if it works as intended!

**Comment by readtedium** [comment] 2024-05-22 22:24
Confirm it works, thank you @xerz-one!

Closing this one.

**Closed as completed by readtedium** 2024-05-22 22:24 UTC
